#!/bin/sh
set -e

cpan_install() {
   local perlmod="$1"
   perl -M"$perlmod" -e '1;' > /dev/null 2>&1 && echo "$perlmod already installed"
   perl -M"$perlmod" -e '1;' > /dev/null 2>&1 || cpan install "$perlmod"
}

perlmodules='
Cwd Data::Dump Digest::SHA File::Path File::Slurp File::Spec File::Temp
FindBin Getopt::Long IO::CaptureOutput IO::Socket::INET Image::Magick
JSON LWP::UserAgent LWP::Protocol::https Template YAML DateTime
Email::Simple Email::Sender
'

if [ -f /etc/debian_version ]
then
   apt-get install -y xvfb python-virtualenv
   apt-get install -y libdata-dump-perl libdigest-sha-perl libfile-slurp-perl \
	   libfile-spec-perl libio-captureoutput-perl perlmagick libjson-perl \
	    libwww-perl libtemplate-perl libyaml-perl libdatetime-perl \
            libemail-sender-perl libemail-simple-perl
   apt-get install -y libgtk2.0-0
   if lsb_release -i | grep -q Debian
   then
       apt-get install iceweasel
   fi
fi

if [ -f /etc/redhat-release ] && which yum > /dev/null 2>&1
then
    yum install -y redhat-lsb-core xorg-x11-server-Xvfb python-virtualenv
    for perlmodule in $perlmodules
    do
        yum install -y "perl($perlmodule)"
    done
    if [ "$(uname -m)" == "x86_64" ]
    then
        yum install -y 'libgtk-x11-2.0.so.0()(64bit)'
    else
        yum install -y libgtk-x11-2.0.so.0
    fi
fi

if [ a$(uname -o) = aCygwin ]
then
    for perlmod in $perlmodules
    do
        cpan_install $perlmod
    done
fi
