#!/bin/sh
set -e

cpan_install() {
   local perlmod="$1"
   perl -M"$perlmod" -e '1;' > /dev/null 2>&1 && echo "$perlmod already installed"
   perl -M"$perlmod" -e '1;' > /dev/null 2>&1 || cpan install "$perlmod"
}

yum_install() {
    for package in "$@"
    do
        rpm --quiet -q --whatprovides "$package" || yum install -y "$package"
    done
}

apt_install() {
    apt-get install -y "$@"
}

pkg_install() {
    [ -f /etc/debian_version ] && apt_install "$@"
    [ -f /etc/redhat-release ] && which yum > /dev/null 2>&1 && yum_install "$@"
}

perlmodules='
Cwd Data::Dump Digest::SHA File::Path File::Slurp File::Spec File::Temp
FindBin Getopt::Long IO::CaptureOutput IO::Socket::INET Image::Magick
JSON LWP::UserAgent LWP::Protocol::https Template YAML::Syck DateTime
Email::Simple Email::Sender File::Type IPC::Run XML::LibXML
'

if [ -f /etc/debian_version ]
then
   apt-get install -y ntp xvfb python-virtualenv
   apt-get install -y libdata-dump-perl libdigest-sha-perl libfile-slurp-perl \
	   libfile-spec-perl libio-captureoutput-perl perlmagick libjson-perl \
	    libwww-perl libtemplate-perl libyaml-syck-perl libdatetime-perl \
            libemail-sender-perl libemail-simple-perl libfile-type-perl \
            libipc-run-perl libxml-libxml-perl
   apt-get install -y libgtk2.0-0
   apt-get install -y nmap
   if lsb_release -i | grep -q Debian
   then
       apt-get install iceweasel
   fi
fi

if [ -f /etc/redhat-release ] && which yum > /dev/null 2>&1
then
    yum_install ntp redhat-lsb-core xorg-x11-server-Xvfb python-virtualenv
    if lsb_release -i | grep -q Fedora
    then
        yum_install nmap-ncat
    else
        yum_install nmap
    fi
    for perlmodule in $perlmodules
    do
        yum_install "perl($perlmodule)"
    done
    if [ "$(uname -m)" == "x86_64" ]
    then
        yum_install 'libgtk-x11-2.0.so.0()(64bit)'
    else
        yum_install libgtk-x11-2.0.so.0
    fi
    if which systemctl > /dev/null 2>&1
    then
        systemctl enable ntpd.service
        systemctl is-active -q ntpd.service || systemctl start ntpd.service
    else
        chkconfig ntpd on
        service ntpd status > /dev/null 2>&1 || service ntpd start
    fi
fi

if [ a$(uname -o) = aCygwin ]
then
    for perlmod in $perlmodules
    do
        cpan_install $perlmod
    done
fi

install_X() {
    packages="fluxbox"
    if [ -f /etc/debian_version ]
    then
        packages="$packages xserver-xorg-video-dummy xserver-xorg-input-void"
    fi
    if [ -f /etc/redhat-release ]
    then
        packages="$packages xorg-x11-drv-dummy xorg-x11-drv-void.x86_64"
    fi
    pkg_install $packages
}

while test $# != 0
do
    case "$1" in
        X)
            install_X ;;
        *)
            echo "Unknown option $1" >&2 ;;
    esac
    shift
done
