#!/usr/bin/perl -w
use strict;
use FindBin;
use IO::CaptureOutput qw(qxx);
use Cwd;
use English;

sub winpath {
    return $_[0] unless $OSNAME eq 'cygwin';
    my $res = `cygpath -aw $_[0]`;
    chomp $res;
    return $res;
}

my $virtenv_marionette_dir = winpath("$FindBin::Bin/virtualenv-marionette");

sub run {
    system(@_) == 0 || die "Error running " . join(' ', @_);
}

sub run_from_dir {
    my $old_cwd = getcwd;
    chdir shift @_;
    my $res = run(@_);
    chdir $old_cwd;
    return $res;
}

my $virtualenv_cmd = 'virtualenv';
my $bin = 'bin';
if ($OSNAME eq 'cygwin') {
    $bin = 'Scripts';
    $virtualenv_cmd = "$FindBin::Bin/bundle/python/Scripts/virtualenv.exe";
}

run($virtualenv_cmd, $virtenv_marionette_dir) unless -d $virtenv_marionette_dir;
run_from_dir('marionette', "$virtenv_marionette_dir/$bin/python", 'setup.py', 'develop');
