#!/usr/bin/perl -w
use strict;
use FindBin;
use File::Copy;
use IO::CaptureOutput qw(qxx);
use Cwd;
use English;

sub winpath {
    return $_[0] unless $OSNAME eq 'cygwin';
    my $res = `cygpath -aw $_[0]`;
    chomp $res;
    return $res;
}

my $virtenv_marionette_dir = winpath("$FindBin::Bin/virtualenv-marionette-4.3.0");
my $virtenv_pefile_dir = winpath("$FindBin::Bin/virtualenv-pefile");

sub run {
    system(@_) == 0 || die "Error running " . join(' ', @_);
}

sub run_from_dir {
    my $old_cwd = getcwd;
    chdir shift @_;
    my $res = run(@_);
    chdir $old_cwd;
    return $res;
}

my $virtualenv_cmd = 'virtualenv';
my $bin = 'bin';
my $lib = 'lib';
if ($OSNAME eq 'cygwin') {
    $bin = 'Scripts';
    $lib = 'Lib';
    $virtualenv_cmd = "$FindBin::Bin/bundle/python/Scripts/virtualenv.exe";
    run("$FindBin::Bin/bundle/install_virtualenv.sh")
                                        unless -f $virtualenv_cmd;
}

unless (-d $virtenv_marionette_dir) {
    run($virtualenv_cmd, $virtenv_marionette_dir);
    # upgrade pip and setuptools
    run("$virtenv_marionette_dir/$bin/pip", 'install', '--upgrade', 'pip');
    run("$virtenv_marionette_dir/$bin/pip", 'install', '--upgrade', 'setuptools');
    run_from_dir('marionette', "$virtenv_marionette_dir/$bin/python", 'setup.py', 'develop');
    # Workaround for https://bugzilla.mozilla.org/show_bug.cgi?id=1345274
    my $sitepackage = 'site-packages/marionette_harness-4.3.0-py2.7.egg/marionette_harness/runner/';
    my $marionette_runner_dir = "$virtenv_marionette_dir/$lib/python2.7/$sitepackage";
    $marionette_runner_dir = "$virtenv_marionette_dir/$lib/$sitepackage"
                unless -d $marionette_runner_dir;
    copy "$FindBin::Bin/data/marionette_certs/test.cert", $marionette_runner_dir;
    copy "$FindBin::Bin/data/marionette_certs/test.key", $marionette_runner_dir;
}

if ($OSNAME eq 'cygwin') {
    unless (-d $virtenv_pefile_dir) {
        run($virtualenv_cmd, $virtenv_pefile_dir);
        run("$virtenv_pefile_dir/$bin/pip", 'install', 'pefile');
    }
}
