from marionette_harness import MarionetteTestCase
import testsuite

class Test(testsuite.TorBrowserTest):

    def setUp(self):
        testsuite.TorBrowserTest.setUp(self)

        self.marionette.set_pref("network.proxy.allow_hijacking_localhost", False)
        self.test_page_file_url = self.marionette.absolute_url("dom-objects-enumeration.html?testType=worker")

        self.expectedObjects = [
                "AbortController",
                "AbortSignal",
                "addEventListener",
                "Array",
                "ArrayBuffer",
                "atob",
                "Atomics",
                "BigInt",
                "BigInt64Array",
                "BigUint64Array",
                "Blob",
                "Boolean",
                "BroadcastChannel",
                "btoa",
                "ByteLengthQueuingStrategy",
                "Cache",
                "caches",
                "CacheStorage",
                "clearInterval",
                "clearTimeout",
                "close",
                "CloseEvent",
                "console",
                "constructor",
                "CountQueuingStrategy",
                "createImageBitmap",
                "crossOriginIsolated",
                "crypto",
                "Crypto",
                "CustomEvent",
                "DataView",
                "Date",
                "decodeURI",
                "decodeURIComponent",
                "DedicatedWorkerGlobalScope",
                "__defineGetter__",
                "__defineSetter__",
                "Directory",
                "dispatchEvent",
                "DOMException",
                "DOMMatrix",
                "DOMMatrixReadOnly",
                "DOMPoint",
                "DOMPointReadOnly",
                "DOMQuad",
                "DOMRect",
                "DOMRectReadOnly",
                "DOMRequest",
                "DOMStringList",
                "dump",
                "encodeURI",
                "encodeURIComponent",
                "Error",
                "ErrorEvent",
                "escape",
                "eval",
                "EvalError",
                "Event",
                "EventSource",
                "EventTarget",
                "fetch",
                "File",
                "FileList",
                "FileReader",
                "FileReaderSync",
                "Float32Array",
                "Float64Array",
                "FormData",
                "Function",
                "globalThis",
                "hasOwnProperty",
                "Headers",
                "IDBCursor",
                "IDBCursorWithValue",
                "IDBDatabase",
                "IDBFactory",
                "IDBIndex",
                "IDBKeyRange",
                "IDBObjectStore",
                "IDBOpenDBRequest",
                "IDBRequest",
                "IDBTransaction",
                "IDBVersionChangeEvent",
                "ImageBitmap",
                "ImageBitmapRenderingContext",
                "ImageData",
                "importScripts",
                "indexedDB",
                "Infinity",
                "Int16Array",
                "Int32Array",
                "Int8Array",
                "InternalError",
                "Intl",
                "isFinite",
                "isNaN",
                "isPrototypeOf",
                "isSecureContext",
                "JSON",
                "location",
                "__lookupGetter__",
                "__lookupSetter__",
                "Map",
                "Math",
                "MediaCapabilities",
                "MediaCapabilitiesInfo",
                "MessageChannel",
                "MessageEvent",
                "MessagePort",
                "name",
                "NaN",
                "navigator",
                "Notification",
                "Number",
                "Object",
                "onerror",
                "onlanguagechange",
                "onmessage",
                "onmessageerror",
                "onoffline",
                "ononline",
                "onrejectionhandled",
                "onunhandledrejection",
                "origin",
                "parseFloat",
                "parseInt",
                "performance",
                "Performance",
                "PerformanceEntry",
                "PerformanceMark",
                "PerformanceMeasure",
                "PerformanceObserver",
                "PerformanceObserverEntryList",
                "PerformanceResourceTiming",
                "PerformanceServerTiming",
                "postMessage",
                "ProgressEvent",
                "Promise",
                "PromiseRejectionEvent",
                "propertyIsEnumerable",
                "__proto__",
                "Proxy",
                "queueMicrotask",
                "RangeError",
                "ReadableStream",
                "ReferenceError",
                "Reflect",
                "RegExp",
                "removeEventListener",
                "Request",
                "Response",
                "self",
                "Set",
                "setInterval",
                "setTimeout",
                "StorageManager",
                "String",
                "SubtleCrypto",
                "Symbol",
                "SyntaxError",
                "TextDecoder",
                "TextEncoder",
                "toLocaleString",
                "toString",
                "TypeError",
                "Uint16Array",
                "Uint32Array",
                "Uint8Array",
                "Uint8ClampedArray",
                "undefined",
                "unescape",
                "URIError",
                "URL",
                "URLSearchParams",
                "valueOf",
                "WeakMap",
                "WeakSet",
                "WebAssembly",
                "WebSocket",
                "Worker",
                "WorkerGlobalScope",
                "WorkerLocation",
                "WorkerNavigator",
                "XMLHttpRequest",
                "XMLHttpRequestEventTarget",
                "XMLHttpRequestUpload",
                ]
        self.expectedObjects80 = self.expectedObjects + ["AggregateError", "FinalizationRegistry", "WeakRef"]
        self.expectedObjects80.sort()

    def test_dom_objects_enumeration_workers(self):
        expectedObjects = self.expectedObjects
        if self.get_version() >= 80:
            expectedObjects = self.expectedObjects80

        with self.marionette.using_context('content'):
            self.marionette.navigate(self.test_page_file_url)
            self.marionette.timeout.implicit = 5
            elt = self.marionette.find_element('id', 'enumeration')
            r = elt.text.split("\n")
            err = False
            unknown_objects = ''
            for l in r:
                if l in expectedObjects:
                    continue
                err = True
                unknown_objects += l + "\n"

            err_msg = "Unknown objects:\n%s" % unknown_objects
            self.assertFalse(err, msg=err_msg)

            for l in expectedObjects:
                if l in r:
                    continue
                err = True
                unknown_objects += l + "\n"

            err_msg = "Expected objects not found:\n%s" % unknown_objects
            self.assertFalse(err, msg=err_msg)