from marionette_driver import By
from marionette_driver.errors import MarionetteException

from marionette_harness import MarionetteTestCase

import testsuite


class Test(MarionetteTestCase):

    def setUp(self):
        MarionetteTestCase.setUp(self)

        ts = testsuite.TestSuite()
        self.ts = ts

        self.expectedObjects = [
                "addEventListener",
                "Array",
                "ArrayBuffer",
                "atob",
                "Blob",
                "Boolean",
                "BroadcastChannel",
                "btoa",
                "Cache",
                "caches",
                "CacheStorage",
                "clearInterval",
                "clearTimeout",
                "close",
                "console",
                "constructor",
                "createImageBitmap",
                "DataView",
                "Date",
                "decodeURI",
                "decodeURIComponent",
                "DedicatedWorkerGlobalScope",
                "__defineGetter__",
                "__defineSetter__",
                "dispatchEvent",
                "DOMCursor",
                "DOMError",
                "DOMException",
                "DOMRequest",
                "DOMStringList",
                "dump",
                "encodeURI",
                "encodeURIComponent",
                "Error",
                "escape",
                "eval",
                "EvalError",
                "Event",
                "EventTarget",
                "fetch",
                "File",
                "FileReaderSync",
                "Float32Array",
                "Float64Array",
                "FormData",
                "Function",
                "getAllPropertyNames",
                "hasOwnProperty",
                "Headers",
                "IDBCursor",
                "IDBCursorWithValue",
                "IDBDatabase",
                "IDBFactory",
                "IDBIndex",
                "IDBKeyRange",
                "IDBObjectStore",
                "IDBOpenDBRequest",
                "IDBRequest",
                "IDBTransaction",
                "IDBVersionChangeEvent",
                "ImageBitmap",
                "ImageData",
                "importScripts",
                "indexedDB",
                "Infinity",
                "Int16Array",
                "Int32Array",
                "Int8Array",
                "InternalError",
                "Intl",
                "isFinite",
                "isNaN",
                "isPrototypeOf",
                "Iterator",
                "JSON",
                "location",
                "__lookupGetter__",
                "__lookupSetter__",
                "Map",
                "Math",
                "MessageChannel",
                "MessageEvent",
                "MessagePort",
                "NaN",
                "navigator",
                "Notification",
                "Number",
                "Object",
                "onclose",
                "onerror",
                "onmessage",
                "onoffline",
                "ononline",
                "parseFloat",
                "parseInt",
                "performance",
                "Performance",
                "PerformanceEntry",
                "PerformanceMark",
                "PerformanceMeasure",
                "postMessage",
                "Promise",
                "propertyIsEnumerable",
                "__proto__",
                "Proxy",
                "RangeError",
                "ReferenceError",
                "Reflect",
                "RegExp",
                "removeEventListener",
                "Request",
                "Response",
                "self",
                "Set",
                "setInterval",
                "setTimeout",
                "StopIteration",
                "String",
                "Symbol",
                "SyntaxError",
                "TextDecoder",
                "TextEncoder",
                "toLocaleString",
                "toSource",
                "toString",
                "TypeError",
                "Uint16Array",
                "Uint32Array",
                "Uint8Array",
                "Uint8ClampedArray",
                "undefined",
                "unescape",
                "uneval",
                "unwatch",
                "URIError",
                "URL",
                "URLSearchParams",
                "valueOf",
                "watch",
                "WeakMap",
                "WeakSet",
                "WebSocket",
                "Worker",
                "WorkerGlobalScope",
                "WorkerLocation",
                "WorkerNavigator",
                "XMLHttpRequest",
                "XMLHttpRequestEventTarget",
                "XMLHttpRequestUpload",
                ]

    def test_dom_objects_enumeration_workers(self):
        with self.marionette.using_context('content'):
            URL = "file://%s/workers/dom-objects-enumeration.html" % self.ts.t['options']['test_data_dir']
            self.marionette.navigate(URL)
            self.marionette.set_search_timeout(50000)
            elt = self.marionette.find_element('id', 'enumeration')

            err = False
            unknown_objects = ''
            for l in elt.text.split("\n"):
                if l in self.expectedObjects:
                    continue
                err = True
                unknown_objects += l + "\n"

            err_msg = "Unknown objects:\n%s" % unknown_objects
            self.assertFalse(err, msg=err_msg)
