#!/bin/sh
set -e
basedir=$(cd $(dirname $0); pwd)
cd "$basedir/.."
if ! [ -d .git ]
then
    if ! [ -f bundle/bundle_commit.txt ]
    then
        echo 'file bundle/bundle_commit.txt is missing' 1>&2
        exit 1
    fi
    bundle_commit=$(cat bundle/bundle_commit.txt)
    git init
    git remote add origin https://gitlab.torproject.org/tpo/applications/tor-browser-bundle-testsuite.git
    git fetch origin
    git branch main $bundle_commit
    git branch --set-upstream-to=origin/main main
    git reset main
fi
git config --replace-all --local gpg.program "$basedir/gpggit"
if ! git symbolic-ref -q HEAD > /dev/null
then
    # checkout origin/main if we are not on a branch
    remote="${1:-origin}"
    branch="${2:-main}"
    git fetch "$remote"
    git verify-commit "$remote/$branch"
    git checkout "$remote/$branch"
else
    git pull --verify-signatures "$@"
fi
git submodule init
git submodule update
